<h2> Back Propagation - ANN 

In [1]:
import numpy as np
X = np.array(([2, 9], [1, 5], [3, 6]), dtype=float)
Y = np.array(([92], [86], [89]), dtype=float)
X = X/np.amax(X, axis=0)
actual_output = Y / 100
print(actual_output)

[[0.92]
 [0.86]
 [0.89]]


In [2]:
def sigmoid(x):
    return 1/(1 + np.exp(-x))

def derivatives_sigmoid(x):
    return x * (1 - x)

In [3]:
#initialization
epoch = 1000
learning_rate = 0.15
inputlayer_neurons = 2
hiddenlayer_neurons = 3
outputlayer_neurons = 1

# Weight of hidden layer
wh = np.random.uniform(low=-0.05,high=0.05,size=(inputlayer_neurons, hiddenlayer_neurons))#2x3

# Bias of hidden layer
bh = np.random.uniform(low=-0.05,high=0.05,size=(1, hiddenlayer_neurons))

# Weight of output layer
wo = np.random.uniform(low=-0.05,high=0.05, size=(hiddenlayer_neurons, outputlayer_neurons))

# Bias of output layer
bo = np.random.uniform(low=-0.05,high=0.05,size=(1, outputlayer_neurons))

In [4]:
# training
for i in range(epoch):
    # Sum of (input * weights in hidden layer) + bias of hidden
    net_h = np.dot(X, wh) + bh

    # Apply Activation Function
    sigma_h = sigmoid(net_h)
    # Input to O/P Layer = (O/P of Hidden Layer * weight of O/P Layer) + bias of O/P layer
    net_o = np.dot(sigma_h, wo) + bo
    # Apply Activation Function
    output = sigmoid(net_o)
    
 #Backpropagation
 # Error at Output layer
    eo = actual_output-output # Error at o/p
    outgrad = derivatives_sigmoid(output)
    d_output = eo* outgrad # Errj=Oj(1-Oj)(Tj-Oj)
    #print("the d_output is",d_output)

# Error at Hidden later
    eh = d_output.dot(wo.T) # .T means transpose
    hiddengrad = derivatives_sigmoid(sigma_h) # How much hidden layer wts contributed to error
    d_hidden = eh * hiddengrad
    wo += sigma_h.T.dot(d_output) *learning_rate # Dotproduct of nextlayererror and currentlayerop
    wh += X.T.dot(d_hidden) *learning_rate
    
    sum_error = 0
    
    for j in range(len(actual_output)):
        print(output[j],actual_output[j] )
        sum_error+=((output[j] - actual_output[j])**2)
    sum_error/=2
    
    print(f'Epoch {i} error {sum_error}')

[0.49770545] [0.92]
[0.49771241] [0.86]
[0.49767685] [0.89]
Epoch 0 error [0.23175122]
[0.50594363] [0.92]
[0.50593408] [0.86]
[0.50586411] [0.89]
Epoch 1 error [0.22218287]
[0.51401009] [0.92]
[0.51398241] [0.86]
[0.51388071] [0.89]
Epoch 2 error [0.21301085]
[0.52190447] [0.92]
[0.52185564] [0.86]
[0.52172629] [0.89]
Epoch 3 error [0.20422359]
[0.52962687] [0.92]
[0.52955269] [0.86]
[0.52940094] [0.89]
Epoch 4 error [0.19580914]
[0.53717784] [0.92]
[0.53707314] [0.86]
[0.53690523] [0.89]
Epoch 5 error [0.18775524]
[0.54455833] [0.92]
[0.54441714] [0.86]
[0.54424009] [0.89]
Epoch 6 error [0.18004945]
[0.55176963] [0.92]
[0.55158532] [0.86]
[0.5514068] [0.89]
Epoch 7 error [0.17267929]
[0.55881333] [0.92]
[0.55857883] [0.86]
[0.55840695] [0.89]
Epoch 8 error [0.16563224]
[0.56569128] [0.92]
[0.56539918] [0.86]
[0.56524239] [0.89]
Epoch 9 error [0.15889591]
[0.57240558] [0.92]
[0.57204827] [0.86]
[0.5719152] [0.89]
Epoch 10 error [0.15245801]
[0.57895853] [0.92]
[0.5785283] [0.86]
[0.57

In [5]:
print("Normalized Input: \n" + str(X))
print("Actual Output: \n" + str(actual_output))
print("Predicted Output: \n" ,output)

Normalized Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
 [[0.89668031]
 [0.87860037]
 [0.89452723]]
