<h2> Back Propagation - ANN 

In [2]:
import numpy as np
X = np.array(([2, 9], [1, 5], [3, 6]), dtype=float)
Y = np.array(([92], [86], [89]), dtype=float)
X = X/np.amax(X, axis=0)
actual_output = Y / 100
print(X)
print(actual_output)

[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
[[0.92]
 [0.86]
 [0.89]]


In [5]:
def sigmoid(x):
    return 1/(1 + np.exp(-x))

def derivatives_sigmoid(x):
    return x * (1 - x)

In [6]:
#initialization
epoch = 1000
learning_rate = 0.15
inputlayer_neurons = 2
hiddenlayer_neurons = 3
outputlayer_neurons = 1

# Weight of hidden layer
wh = np.random.uniform(low=-0.05,high=0.05,size=(inputlayer_neurons, hiddenlayer_neurons))#2x3

# Bias of hidden layer
bh = np.random.uniform(low=-0.05,high=0.05,size=(1, hiddenlayer_neurons))

# Weight of output layer
wo = np.random.uniform(low=-0.05,high=0.05, size=(hiddenlayer_neurons, outputlayer_neurons))

# Bias of output layer
bo = np.random.uniform(low=-0.05,high=0.05,size=(1, outputlayer_neurons))

In [7]:
# training
for i in range(epoch):
    # Sum of (input * weights in hidden layer) + bias of hidden
    net_h = np.dot(X, wh) + bh

    # Apply Activation Function
    sigma_h = sigmoid(net_h)
    # Input to O/P Layer = (O/P of Hidden Layer * weight of O/P Layer) + bias of O/P layer
    net_o = np.dot(sigma_h, wo) + bo
    # Apply Activation Function
    output = sigmoid(net_o)
    
 #Backpropagation
 # Error at Output layer
    eo = actual_output-output # Error at o/p
    outgrad = derivatives_sigmoid(output)
    d_output = eo* outgrad # Errj=Oj(1-Oj)(Tj-Oj)
    #print("the d_output is",d_output)

# Error at Hidden later
    eh = d_output.dot(wo.T) # .T means transpose
    hiddengrad = derivatives_sigmoid(sigma_h) # How much hidden layer wts contributed to error
    d_hidden = eh * hiddengrad
    wo += sigma_h.T.dot(d_output) *learning_rate # Dotproduct of nextlayererror and currentlayerop
    wh += X.T.dot(d_hidden) *learning_rate
    
    sum_error = 0
    
    for j in range(len(actual_output)):
        print(output[j],actual_output[j] )
        sum_error+=((output[j] - actual_output[j])**2)
    sum_error/=2
    
    print(f'Epoch {i} error {sum_error}')

[0.50400314] [0.92]
[0.50385829] [0.86]
[0.50399218] [0.89]
Epoch 0 error [0.22444617]
[0.51176798] [0.92]
[0.5116649] [0.86]
[0.51174775] [0.89]
Epoch 1 error [0.21553274]
[0.51936648] [0.92]
[0.51930434] [0.86]
[0.51933721] [0.89]
Epoch 2 error [0.20698583]
[0.52679963] [0.92]
[0.52677612] [0.86]
[0.52676147] [0.89]
Epoch 3 error [0.19879346]
[0.53406875] [0.92]
[0.5340803] [0.86]
[0.53402181] [0.89]
Epoch 4 error [0.19094352]
[0.54117544] [0.92]
[0.5412174] [0.86]
[0.54111979] [0.89]
Epoch 5 error [0.1834239]
[0.54812154] [0.92]
[0.54818838] [0.86]
[0.54805722] [0.89]
Epoch 6 error [0.17622247]
[0.55490913] [0.92]
[0.55499454] [0.86]
[0.55483614] [0.89]
Epoch 7 error [0.16932724]
[0.56154045] [0.92]
[0.56163756] [0.86]
[0.56145876] [0.89]
Epoch 8 error [0.16272637]
[0.56801789] [0.92]
[0.56811937] [0.86]
[0.56792747] [0.89]
Epoch 9 error [0.15640821]
[0.57434398] [0.92]
[0.57444217] [0.86]
[0.57424476] [0.89]
Epoch 10 error [0.15036137]
[0.58052134] [0.92]
[0.58060838] [0.86]
[0.580

In [8]:
print("Normalized Input: \n" + str(X))
print("Actual Output: \n" + str(actual_output))
print("Predicted Output: \n" ,output)

Normalized Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
 [[0.89595662]
 [0.87930689]
 [0.89460711]]
