<h2> K Nearest Neighbours - KNN 

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
#load iris dataset
from sklearn.datasets import load_iris
iris=load_iris()
X=iris.data # features
y=iris.target # target

In [2]:
#split the dataset into train and test data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20 , random_state =23)
print(iris.data.shape)
print('Training Set', len(X_train))
print('Test Set', len(X_test))

(150, 4)
Training Set 120
Test Set 30


In [4]:
#to train the model
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=1)
knn.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=1)

In [5]:
#make prediction on test data, Classify
y_pred=knn.predict(X_test)
print(y_pred)

[2 2 1 0 2 1 0 2 0 1 1 0 2 0 0 1 1 1 2 0 2 0 0 0 2 0 0 2 1 1]


In [6]:
#compare the accuracy between the predicted and the actual output y_test
from sklearn import metrics
print("accuracy=",metrics.accuracy_score(y_pred,y_test))
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

accuracy= 0.9666666666666667
[[12  0  0]
 [ 0  8  0]
 [ 0  1  9]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       0.89      1.00      0.94         8
           2       1.00      0.90      0.95        10

    accuracy                           0.97        30
   macro avg       0.96      0.97      0.96        30
weighted avg       0.97      0.97      0.97        30



In [7]:
#to compare the actual and predicted are correct or wrong
predicted=knn.predict(X_test)
#create a list for all the predicted one target name
pre_target=[iris.target_names[i] for i in predicted]
print("pre_target=",pre_target,"\n\n")
#create a list for all the target names of y_test data
actual_target=[iris.target_names[i] for i in y_test]
print("actual_target =",actual_target,"\n\n")
print("\t Predicted","\t\tActual","\t\t\tAnswer")
for i in range(0,len(pre_target)):
    print(i,":",pre_target[i],"\t\t",actual_target[i],"\t\t",end='\t')
    if(pre_target[i]==actual_target[i]):
        print("Yes")
    else:
        print("No")

pre_target= ['virginica', 'virginica', 'versicolor', 'setosa', 'virginica', 'versicolor', 'setosa', 'virginica', 'setosa', 'versicolor', 'versicolor', 'setosa', 'virginica', 'setosa', 'setosa', 'versicolor', 'versicolor', 'versicolor', 'virginica', 'setosa', 'virginica', 'setosa', 'setosa', 'setosa', 'virginica', 'setosa', 'setosa', 'virginica', 'versicolor', 'versicolor'] 


actual_target = ['virginica', 'virginica', 'versicolor', 'setosa', 'virginica', 'versicolor', 'setosa', 'virginica', 'setosa', 'versicolor', 'versicolor', 'setosa', 'virginica', 'setosa', 'setosa', 'virginica', 'versicolor', 'versicolor', 'virginica', 'setosa', 'virginica', 'setosa', 'setosa', 'setosa', 'virginica', 'setosa', 'setosa', 'virginica', 'versicolor', 'versicolor'] 


	 Predicted 		Actual 			Answer
0 : virginica 		 virginica 			Yes
1 : virginica 		 virginica 			Yes
2 : versicolor 		 versicolor 			Yes
3 : setosa 		 setosa 			Yes
4 : virginica 		 virginica 			Yes
5 : versicolor 		 versicolor 			Yes
6 : se